#!/usr/bin/env python3
"""Regenerate or verify the checked-in reviewed QuantCheck fixture.

The fixture itself is produced entirely by
``quantcheck.fixtures.canonical_reviewed_fixture_bytes`` — a pure, offline,
deterministic function. This script only resolves the checked-in file path
and either writes the regenerated bytes or verifies them against what is
already committed.

Usage:

    uv run python scripts/generate_reviewed_fixture.py            # write
    uv run python scripts/generate_reviewed_fixture.py --check    # verify only
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from quantcheck.fixtures import DEFAULT_FIXTURE_SEED, canonical_reviewed_fixture_bytes

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURE_PATH = REPO_ROOT / "tests" / "fixtures" / "reviewed_financial_facts.json"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the checked-in fixture matches regenerated bytes; do not write",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=DEFAULT_FIXTURE_SEED,
        help=f"fixture seed (default: {DEFAULT_FIXTURE_SEED}, the checked-in seed)",
    )
    args = parser.parse_args(argv)

    regenerated = canonical_reviewed_fixture_bytes(seed=args.seed)

    if args.check:
        if not FIXTURE_PATH.exists():
            print(f"missing checked-in fixture: {FIXTURE_PATH}", file=sys.stderr)
            return 1
        current = FIXTURE_PATH.read_bytes()
        if current != regenerated:
            print(
                f"{FIXTURE_PATH} is out of date; rerun without --check to regenerate it",
                file=sys.stderr,
            )
            return 1
        print(f"{FIXTURE_PATH} matches regenerated canonical bytes")
        return 0

    FIXTURE_PATH.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE_PATH.write_bytes(regenerated)
    print(f"wrote {FIXTURE_PATH} ({len(regenerated)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
